In [63]:
import pandas as pd
import math
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np

In [64]:
def euclidean_distance(x_1,x_1a,x_2,x_2a):
    delta_x = (x_1a-x_1)**2
    delta_y = (x_2a-x_2)**2
    return math.sqrt(delta_x + delta_y)

In [65]:
data = pd.read_excel('Data_Set_1304211035.xlsx')
dataku = data[['x1','x2']]
dataku

x1  x2
0   1  40
1  28  44
2  15  16
3  16  31
4  21   9
5  11  47
6  30  33
7  10  28
8  20   3
9  31  13

In [66]:
class_1 = []
class_2 = []
centroidc1_x1 = 1
centroidc1_x2 = 28
centroidc2_x1 = 16
centroidc2_x2 = 17

for i in range(4):
    print(centroidc1_x1)
    print(centroidc1_x2)
    print(centroidc2_x1)
    print(centroidc2_x2)
    class_1 = []
    class_2 = []
    for _,row in dataku.iterrows():
        c1 = euclidean_distance(row['x1'],centroidc1_x1,row['x2'],centroidc1_x2)
        c2 =  euclidean_distance(row['x1'],centroidc1_x2,row['x2'],centroidc2_x2)

        if c1 < c2 :
            class_1.append({'x1':row['x1'],'x2':row['x2']})
        elif c2 < c1 :
            class_2.append({'x1':row['x1'],'x2':row['x2']})

    
    sum_c1_x1 = 0
    sum_c1_x2 = 0
    sum_c2_x1 = 0
    sum_c2_x2 = 0
    print(class_1)
    print(class_2)

    for c_1 in class_1:
        sum_c1_x1 += c_1['x1']
        sum_c1_x2 += c_1['x2']
    
    for c_2 in class_2:
        sum_c2_x1 += c_2['x1']
        sum_c2_x2 += c_2['x2']
    
    centroidc1_x1 = sum_c1_x1/len(class_1)
    centroidc1_x2 = sum_c1_x2/len(class_1)
    centroidc2_x1 = sum_c2_x1/len(class_2)
    centroidc2_x2 = sum_c2_x2/len(class_2)


    


1
28
16
17
4
6
9.5
36.5
24.166666666666668
19.666666666666668
6
4
13.5
34.333333333333336
25.5
14.5
7
3
15.857142857142858
34.142857142857146
24.0
8.333333333333334
7
3


In [30]:
class_1

[{'x1': 1, 'x2': 40},
 {'x1': 28, 'x2': 44},
 {'x1': 15, 'x2': 16},
 {'x1': 16, 'x2': 31},
 {'x1': 11, 'x2': 47},
 {'x1': 30, 'x2': 33},
 {'x1': 10, 'x2': 28}]

In [31]:
class_2

[{'x1': 21, 'x2': 9}, {'x1': 20, 'x2': 3}, {'x1': 31, 'x2': 13}]

In [59]:
data_kmeans = dataku.values
datacentroid = pd.read_excel('Data_Set_1304211035.xlsx',sheet_name='Centroid')[['x1-centroid-1','x2-centroid-1','x1-centroid-2','x2-centroid-2']].values[0].reshape(2,2)
centroid = np.array([1,28,16,17]).reshape(2,2)

In [60]:
datacentroid

array([[ 1., 28.],
       [16., 17.]])

In [61]:
for i in range(4):
    k = KMeans(n_clusters=2,init=datacentroid,n_init=1,max_iter=1)
    k.fit(data_kmeans)
    print(k.cluster_centers_)
    datacentroid = k.cluster_centers_

[[ 7.33333333 38.33333333]
 [23.         21.28571429]]
[[13.2 38. ]
 [23.4 14.8]]
[[16.         37.16666667]
 [21.75       10.25      ]]
[[16.         37.16666667]
 [21.75       10.25      ]]
